image: gitpod/workspace-full:latest

tasks:
  - init: |
      git clone https://github.com/flutter/flutter.git -b stable $HOME/flutter
      echo 'export PATH="$HOME/flutter/bin:$PATH"' >> ~/.bashrc
      echo 'export PATH="$HOME/flutter/bin:$PATH"' >> ~/.profile
      export PATH="$HOME/flutter/bin:$PATH"
      flutter doctor
    command: |
      export PATH="$HOME/flutter/bin:$PATH"
      flutter pub get
      flutter run -d chrome

ports:
  - port: 5000
    onOpen: open-preview

vscode:
  extensions:
    - dart-code.flutter
