
name: courses_web
description: Application Flutter Web minimaliste pour suivi des dépenses
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  js: ^0.6.7
  idb_shim: ^2.0.0
  # Versions spécifiques pour Flutter Web
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_core_web: ^2.10.0  # Ajoutez cette ligne
  firebase_auth_web: ^5.8.12  # Ajoutez cette ligne
  
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  
