
name: courses_web
description: Application Flutter Web minimaliste pour suivi des dépenses
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  js: ^0.6.7
  idb_shim: ^2.0.0
  # Supabase - version stable
  supabase_flutter: ^2.3.4
  
  # State management
  provider: ^6.1.1
  intl: ^0.20.2
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  
